### ISSUE TITLE
ClassNotFoundException in the linux release

### ISSUE THREAD

**Issue by darekjanik** [OrangoMango/Snake#1]
I tried to run Linux version (snake_2.0-1_amd64.deb), but unfortunately I get an error:

> Error: Could not find or load main class com.orangomango.snake.Launcher
> Caused by: java.lang.ClassNotFoundException: com.orangomango.snake.Launcher

Technically there's no Launcher.class in the JAR file

**Comment by OrangoMango** [comment]
Hi, yes you are right, I'm really sorry. I forgot to include the Launcher.java file in the executable binaries.
I updated the release with the new executables. Let me know if it works. I tested the arm64 and it works.

**Comment by darekjanik** [comment]
Now it works perfectly. Thanks for the quick fix

**Comment by OrangoMango** [comment]
And thanks for pointing it out 😅
